package com.anafthdev.tfcompose.foundation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF755B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE08E)
val md_theme_light_onPrimaryContainer = Color(0xFF241A00)
val md_theme_light_secondary = Color(0xFF695D3F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF2E1BB)
val md_theme_light_onSecondaryContainer = Color(0xFF231B04)
val md_theme_light_tertiary = Color(0xFF47664A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC9ECC8)
val md_theme_light_onTertiaryContainer = Color(0xFF04210B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F8Fd)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFECE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7E7667)
val md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFEBC248)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF755B00)

val md_theme_dark_primary = Color(0xFFEBC248)
val md_theme_dark_onPrimary = Color(0xFF3D2E00)
val md_theme_dark_primaryContainer = Color(0xFF584400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE08E)
val md_theme_dark_secondary = Color(0xFFD5C5A1)
val md_theme_dark_onSecondary = Color(0xFF392F15)
val md_theme_dark_secondaryContainer = Color(0xFF51462A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF2E1BB)
val md_theme_dark_tertiary = Color(0xFFADCFAD)
val md_theme_dark_onTertiary = Color(0xFF1A361F)
val md_theme_dark_tertiaryContainer = Color(0xFF304D33)
val md_theme_dark_onTertiaryContainer = Color(0xFFC9ECC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE8E1D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE8E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC5B4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E1D9)
val md_theme_dark_inversePrimary = Color(0xFF755B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFEBC248)

val black01 = Color(0xFF020202)
val black02 = Color(0xFF1C1C1C)
val black03 = Color(0xFF353535)
val black04 = Color(0xFF4F4F4F)
val black05 = Color(0xFF686868)
val black06 = Color(0xFF818181)
val black07 = Color(0xFF9A9A9A)
val black08 = Color(0xFFB3B3B3)
val black09 = Color(0xFFCDCDCD)
val black10 = Color(0xFFF0F0F0)

val seed = Color(0xFFFFE5A5)
